<?xml version="1.0" encoding="UTF-8" ?>

<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    
    <title>hwbnju.com</title>
    
    <link>http://hwbnju.com</link>
    <description>nju520's Blog</description>
    <language>en-uk</language>
    <managingEditor> nju520</managingEditor>
    <atom:link href="rss" rel="self" type="application/rss+xml" />
    
<item>
  <title>Promise 点滴</title>
  <link>//javascript-promise</link>
  <author>nju520</author>
  <pubDate>2017-12-05T00:00:00+08:00</pubDate>
  <guid>//javascript-promise</guid>
  <description><![CDATA[
  <h2 id="promise的含义">Promise的含义</h2>

<p>Promise是JavaScript语言早有实现，ES6将其写进了语言标准，统一了用法，原生提供了Promies对象。</p>

<p>所谓Promise，就是一个对象，用来传递异步操作的消息。它代表了某个未来才会知道结果的事件（通常是一个异步操作），并且这个事件提供统一的API，可供进一步处理。</p>

<p>Promies对象有一下两个特点。</p>

<ol>
  <li>对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：Pending【/’pendɪŋ/】（进行中）、Resolved【/rɪ’zɒlvd/】（已完成，又称Fulfilled【/fʊl’fɪld/】）和Rejected【rɪ’dʒekt】（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这是Promise这个名字的由来，他的英语意思就是“承诺”，表示其他手段无法改变。</li>
  <li>一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从Pending变为Resolved和从Pending变为Rejected。只有这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。就算改变已经发生了额，你在对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，在去监听，是得不到结果的。</li>
</ol>

<p>有了Promise对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，Promise对象提供统一的接口，使得控制异步操作更加容易。</p>

<p>Promise也有一些缺点。首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。其次，如果设置回调函数，Promise内部抛出的错误，不会反应到外部。第三当处于Pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。</p>

<p>如果某些事件不断地反复发生，一般来说，使用stream模式是比部署Promise更好的选择。</p>

<h3 id="基本用法">基本用法</h3>

<p>ES6规定，Promise对象是一个构造函数，用来生成Promise实例。
下面代码创造了一个Promise实例。</p>

<pre><code class="language-javascript">var promise = new Promise(function(resolve,reject){
    //...some code
    if(/* 异步操作成功 */){
        resolve(value);
    }else{
        reject(error);
    }
});
</code></pre>

<p>Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。他们是两个函数，由JavaScript引擎提供，不用自己部署。
resolve函数的作用是，将Promise对象的状态从“未完成”变成“成功”（即Pending变为Resolved），在在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；reject函数的作用是，将Promise对象的状态“未完成”变为“失败”（即从Pending变为Rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。</p>

<p>Promise实例生成以后，可以用then方法分别指定Resolved状态和Reject状态的回调函数。</p>

<pre><code class="language-javascript">promise.then(function(value){
    //success
},function(value){
    // failure
});
</code></pre>

<p>then方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为Resolved时调用，第二个回调函数是Promise对象的状态变为Reject时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。</p>

<p>下面是一个Promise对象的简单例子。</p>

<pre><code class="language-javascript">function timeout(ms) {
  return new Promise((resolve) =&gt; {
    setTimeout(resolve, ms, 'done');
  });
}
timeout(100).then((value) =&gt; {
  console.log(value);
});
</code></pre>

<p>上面代码中，timeout方法返回一个Promise实例，表示一段时间以后才会发生的结果。过了指定的时间（ms参数）以后，Promise实例的状态变为Resolved，就会触发then方法绑定的回调函数。</p>

<p>下面是一个用Promise对象实现的Ajax操作的例子。</p>

<pre><code class="language-javascript">var getJSON = function(url) {
  var promise = new Promise(function(resolve, reject){
    var client = new XMLHttpRequest();
    client.open("GET", url);
    client.onreadystatechange = handler;
    client.responseType = "json";
    client.setRequestHeader("Accept", "application/json");
    client.send();
    function handler() {
      if (this.status === 200) {
        resolve(this.response);
      } else {
        reject(new Error(this.statusText));
      }
    };
  });
  return promise;
};
getJSON("/posts.json").then(function(json) {
  console.log('Contents: ' + json);
}, function(error) {
  console.error('出错了', error);
});
</code></pre>

<p>上面代码中，getJSON是对XMLHttpRequest对象的封装，用于发出一个针对JSON数据的HTTP请求，并且返回一个Promise对象。需要注意的是，在getJSON内部，resolve函数和reject函数调用时，都带有参数。</p>

<p>如果调用resolve函数和reject函数时带有参数，那么它们的参数会被传递给回调函数。reject函数的参数通常是Error对象的实例，表示抛出的错误；resolve函数的参数除了正常的值以外，还可能是另一个Promise实例，表示异步操作的结果有可能是一个值，也有可能是另一个异步操作，比如像下面这样。</p>

<pre><code class="language-javascript">var p1 = new Promise(function(resolve, reject){
  // ...
});
var p2 = new Promise(function(resolve, reject){
  // ...
  resolve(p1);
})
</code></pre>

<p>上面代码中，p1和p2都是Promise的实例，但是p2的resolve方法将p1作为参数，即一个异步操作的结果是返回另一个异步操作。</p>

<p>注意，这时p1的状态就会传递给p2，也就是说，p1的状态决定了p2的状态。如果p1的状态是Pending，那么p2的回调函数就会等待p1的状态改变；如果p1的状态已经是Resolved或者Rejected，那么p2的回调函数将会立刻执行。</p>

<h3 id="promiseprototypethen">Promise.prototype.then()</h3>

<p>Promise实例具有then方法，也就是说，then方法是定义在原型对象Promise.prototype上的。它的作用是为Promise实例添加状态改变时的回调函数。前面说过，then方法的第一个参数是Resolved状态的回调函数，第二个参数（可选）是Rejected状态的回调函数。</p>

<p>then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。</p>

<pre><code class="language-javascript">getJSON("/posts.json").then(function(json) {
  return json.post;
}).then(function(post) {
  // ...
});
</code></pre>

<p>上面的代码使用then方法，依次指定了两个回调函数。第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数。</p>

<p>采用链式的then，可以指定一组按照次序调用的回调函数。这时，前一个回调函数，有可能返回的还是一个Promise对象（即有异步操作），这时后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用。</p>

<pre><code class="language-javascript">getJSON("/post/1.json").then(function(post) {
  return getJSON(post.commentURL);
}).then(function funcA(comments) {
  console.log("Resolved: ", comments);
}, function funcB(err){
  console.log("Rejected: ", err);
});
</code></pre>

<p>上面代码中，第一个then方法指定的回调函数，返回的是另一个Promise对象。这时，第二个then方法指定的回调函数，就会等待这个新的Promise对象状态发生变化。如果变为Resolved，就调用funcA，如果状态变为Rejected，就调用funcB。</p>

<p>如果采用箭头函数，上面的代码可以写得更简洁。</p>

<pre><code class="language-javascript">getJSON("/post/1.json").then(
  post =&gt; getJSON(post.commentURL)
).then(
  comments =&gt; console.log("Resolved: ", comments),
  err =&gt; console.log("Rejected: ", err)
);
</code></pre>

<h3 id="promiseprototypecatch">Promise.prototype.catch()</h3>

<p>Promise.prototype.catch方法是<code>.then(null, rejection)</code>的别名，用于指定发生错误时的回调函数。</p>

<pre><code class="language-javascript">getJSON("/posts.json").then(function(posts) {
  // ...
}).catch(function(error) {
  // 处理前一个回调函数运行时发生的错误
  console.log('发生错误！', error);
});
</code></pre>

<p>上面代码中，getJSON方法返回一个Promise对象，如果该对象状态变为Resolved，则会调用then方法指定的回调函数；如果异步操作抛出错误，状态就会变为Rejected，就会调用catch方法指定的回调函数，处理这个错误。</p>

<pre><code class="language-javascript">p.then((val) =&gt; console.log("fulfilled:", val))
  .catch((err) =&gt; console.log("rejected:", err));
// 等同于
p.then((val) =&gt; console.log(fulfilled:", val))
  .then(null, (err) =&gt; console.log("rejected:", err));
var promise = new Promise(function(resolve, reject) {
  throw new Error('test')
});
promise.catch(function(error) { console.log(error) });
// Error: test
</code></pre>

<p>上面代码中，Promise抛出一个错误，就被catch方法指定的回调函数捕获。</p>

<p>如果Promise状态已经变成resolved，再抛出错误是无效的。</p>

<pre><code class="language-javascript">var promise = new Promise(function(resolve, reject) {
  resolve("ok");
  throw new Error('test');
});
promise
  .then(function(value) { console.log(value) })
  .catch(function(error) { console.log(error) });
// ok
</code></pre>

<p>上面代码中，Promise在resolve语句后面，再抛出错误，不会被捕获，等于没有抛出。</p>

<p>Promise对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。</p>

<pre><code class="language-javascript">getJSON("/post/1.json").then(function(post) {
  return getJSON(post.commentURL);
}).then(function(comments) {
  // some code
}).catch(function(error) {
  // 处理前面三个Promise产生的错误
});
</code></pre>

<p>上面代码中，一共有三个Promise对象：一个由getJSON产生，两个由then产生。它们之中任何一个抛出的错误，都会被最后一个catch捕获。</p>

<p>跟传统的try/catch代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，即不会有任何反应。</p>

<pre><code class="language-javascript">var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};
someAsyncThing().then(function() {
  console.log('everything is great');
});
</code></pre>

<p>上面代码中，someAsyncThing函数产生的Promise对象会报错，但是由于没有调用catch方法，这个错误不会被捕获，也不会传递到外层代码，导致运行后没有任何输出。</p>

<pre><code class="language-javascript">var promise = new Promise(function(resolve, reject) {
  resolve("ok");
  setTimeout(function() { throw new Error('test') }, 0)
});
promise.then(function(value) { console.log(value) });
// ok
// Uncaught Error: test
</code></pre>

<p>上面代码中，Promise指定在下一轮“事件循环”再抛出错误，结果由于没有指定catch语句，就冒泡到最外层，成了未捕获的错误。</p>

<p>Node.js有一个unhandledRejection事件，专门监听未捕获的reject错误。</p>

<pre><code class="language-javascript">process.on('unhandledRejection', function (err, p) {
  console.error(err.stack)
});
</code></pre>

<p>上面代码中，unhandledRejection事件的监听函数有两个参数，第一个是错误对象，第二个是报错的Promise实例，它可以用来了解发生错误的环境信息。。</p>

<p>需要注意的是，catch方法返回的还是一个Promise对象，因此后面还可以接着调用then方法。</p>

<pre><code class="language-javascript">var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};
someAsyncThing().then(function() {
  return someOtherAsyncThing();
}).catch(function(error) {
  console.log('oh no', error);
}).then(function() {
  console.log('carry on');
});
// oh no [ReferenceError: x is not defined]
// carry on
</code></pre>

<p>上面代码运行完catch方法指定的回调函数，会接着运行后面那个then方法指定的回调函数。</p>

<p>catch方法之中，还能再抛出错误。</p>

<pre><code class="language-javascript">var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};
someAsyncThing().then(function() {
  return someOtherAsyncThing();
}).catch(function(error) {
  console.log('oh no', error);
  // 下面一行会报错，因为y没有声明
  y + 2;
}).then(function() {
  console.log('carry on');
});
// oh no [ReferenceError: x is not defined]
</code></pre>

<p>上面代码中，catch方法抛出一个错误，因为后面没有别的catch方法了，导致这个错误不会被捕获，也不会传递到外层。如果改写一下，结果就不一样了。</p>

<pre><code class="language-javascript">someAsyncThing().then(function() {
  return someOtherAsyncThing();
}).catch(function(error) {
  console.log('oh no', error);
  // 下面一行会报错，因为y没有声明
  y + 2;
}).catch(function(error) {
  console.log('carry on', error);
});
// oh no [ReferenceError: x is not defined]
// carry on [ReferenceError: y is not defined]
</code></pre>

<p>上面代码中，第二个catch方法用来捕获，前一个catch方法抛出的错误。</p>

<h3 id="promiseall">Promise.all()</h3>

<p>Promise.all方法用于将多个Promise实例，包装成一个新的Promise实例。</p>

<pre><code class="language-javascript">var p = Promise.all([p1,p2,p3]);
</code></pre>

<p>上面代码中，Promise.all方法接受一个数组作为参数，p1、p2、p3都是Promise对象的实例。（Promise.all方法的参数不一定是数组，但是必须具有iterator接口，且返回的每个成员都是Promise实例。）</p>

<p>p的状态由p1、p2、p3决定，分成两种情况。</p>

<ol>
  <li>只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。</li>
  <li>只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。
下面是一个具体的例子。</li>
</ol>

<pre><code class="language-javascript">/ 生成一个Promise对象的数组
var promises = [2, 3, 5, 7, 11, 13].map(function(id){
  return getJSON("/post/" + id + ".json");
});
Promise.all(promises).then(function(posts) {
  // ...
}).catch(function(reason){
  // ...
});
</code></pre>

<h3 id="promiserace">Promise.race()</h3>

<p>Promise.race方法同样是将多个Promise实例，包装成一个新的Promise实例。</p>

<pre><code class="language-javascript">var p = Promise.race([p1,p2,p3]);
</code></pre>

<p>上面代码中，只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的Promise实例的返回值，就传递给p的回调函数。</p>

<p>如果Promise.all方法和Promise.race方法的参数，不是Promise实例，就会先调用下面讲到的Promise.resolve方法，将参数转为Promise实例，再进一步处理。</p>

<h3 id="promiseresolve">Promise.resolve()</h3>

<p>有时需要将现有对象转为Promise对象，Promise.resolve方法就起到这个作用。</p>

<pre><code class="language-javascript">var jsPromise = Promise.resolve($.ajax('/whatever.json'));
</code></pre>

<p>上面代码将jQuery生成deferred对象，转为一个新的Promise对象。</p>

<p>如果Promise.resolve方法的参数，不是具有then方法的对象（又称thenable对象），则返回一个新的Promise对象，且它的状态为Resolved。</p>

<pre><code class="language-javascript">var p = Promise.resolve('Hello');
p.then(function (s){
  console.log(s)
});
// Hello
</code></pre>

<p>上面代码生成一个新的Promise对象的实例p。由于字符串Hello不属于异步操作（判断方法是它不是具有then方法的对象），返回Promise实例的状态从一生成就是Resolved，所以回调函数会立即执行。Promise.resolve方法的参数，会同时传给回调函数。</p>

<p>Promise.resolve方法允许调用时不带参数。所以，如果希望得到一个Promise对象，比较方便的方法就是直接调用Promise.resolve方法。</p>

<pre><code class="language-javascript">var p = Promise.resolve();
p.then(function () {
  // ...
});
</code></pre>

<p>上面代码的变量p就是一个Promise对象。
如果Promise.resolve方法的参数是一个Promise实例，则会被原封不动地返回。</p>

<h3 id="promisereject">Promise.reject()</h3>

<p>Promise.reject(reason)方法也会返回一个新的Promise实例，该实例的状态为rejected。Promise.reject方法的参数reason，会被传递给实例的回调函数。</p>

<pre><code class="language-javascript">var p = Promise.reject('出错了');
p.then(null, function (s){
  console.log(s)
});
// 出错了
</code></pre>

<p>上面代码生成一个Promise对象的实例p，状态为rejected，回调函数会立即执行。</p>

<h2 id="generator函数与promise的结合">Generator函数与Promise的结合</h2>

<p>使用Generator函数管理流程，遇到异步操作的时候，通常返回一个Promise对象。</p>

<pre><code class="language-javascript">function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}
var g = function* () {
  try {
    var foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};
function run (generator) {
  var it = generator();
  function go(result) {
    if (result.done) return result.value;
    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(value));
    });
  }
  go(it.next());
}
run(g);
</code></pre>

<p>上面代码的Generator函数g之中，有一个异步操作getFoo，它返回的就是一个Promise对象。函数run用来处理这个Promise对象，并调用下一个next方法。</p>

<h2 id="async函数">async函数</h2>

<p>async函数与Promise、Generator函数一样，是用来取代回调函数、解决异步操作的一种方法。它本质上是Generator函数的语法糖。async函数并不属于ES6，而是被列入了ES7，但是traceur、Babel.js、regenerator等转码器已经支持这个功能，转码后立刻就能使用。</p>

<h2 id="手动实现一个-promise">手动实现一个 Promise</h2>

<p>又到了手动实现一个功能的时刻啦, 直接上代码:</p>

<pre><code class="language-javascript">/*
我们要满足状态只能三种状态：PENDING,FULFILLED,REJECTED三种状态，且状态只能由PENDING=&gt;FULFILLED,或者PENDING=&gt;REJECTED
*/
var PENDING = 0;
var FULFILLED = 1;
var REJECTED = 2;
/*
value状态为执行成功事件的入参
deferreds保存着状态改变之后的需要处理的函数以及promise子节点，
换句话说, defferd保存的是一个对象, 对象中有一个属性指向需要处理的函数, 有一个promise属性 指向子节点

构造函数里面应该包含这三个属性的初始化
 */
function Promise(callback) {
    this.status = PENDING;
    this.value = null;
    this.defferd = [];
    // 虽然 setTimeout传入的延迟时间为0, 但是它仍然是异步执行; 可以将这个延迟时间换成 1000看看结果如何
    //所以返回的一个promise继续执行then函数
    console.log('I am in new Promise ');
    setTimeout(callback.bind(this, this.resolve.bind(this), this.reject.bind(this)), 0);
}

Promise.prototype = {
    constructor: Promise,
    //触发改变promise状态到FULFILLED
    //
    resolve: function (result) {
        this.status = FULFILLED;
        this.value = result;
        this.done();
    },
    //触发改变promise状态到REJECTED
    reject: function (error) {
        this.status = REJECTED;
        this.value = error;
    },
    //处理defferd
    handle: function (fn) {
        if (!fn) {
            return;
        }
        var value = this.value;
        var t = this.status;
        var p;
        if (t == PENDING) {
             this.defferd.push(fn);
        } else {
            if (t == FULFILLED &amp;&amp; typeof fn.onfulfiled == 'function') {
                p = fn.onfulfiled(value);
            }
            if (t == REJECTED &amp;&amp; typeof fn.onrejected == 'function') {
                p = fn.onrejected(value);
            }
        var promise = fn.promise;
        if (promise) {
            if (p &amp;&amp; p.constructor == Promise) {
                // p.defferd = promise2.defferd
                // 传入then中的 new Promise对象的  defferd 再此指向子promise的 defferd
                p.defferd = promise.defferd;
            } else {
                p = this;
                p.defferd = promise.defferd;
                this.done();
            }
        }
        }
    },
    //触发promise defferd 里面需要执行的函数
    done: function () {
        var status = this.status;
        if (status == PENDING) {
            return;
        }
        var defferd = this.defferd;
        // 这个defferd的长度要么是0,要么是1吧!!!
        // 不管 defferd是否为空, 下面的for循环都会至少执行一次
        // 当 defferd 为空时, handle(NULL) 直接return
        // 当 defferd不为空时, handle[defferd[0]]
        for (var i = 0; i &lt; defferd.length; i++) {
            this.handle(defferd[i]);
        }
    },
    /*储存then函数里面的事件
    返回promise对象
    defferd函数当前promise对象里面
    */
    // 链式调用then时, this是子promise, 不是父 promise
    then: function (success, fail) {
      console.log('I am in then function');
       var o = {
            onfulfiled: success,
            onrejected: fail
        };
        var status = this.status;
        o.promise = new this.constructor(function () {

        });
        if (status == PENDING) {
            // promise2.defferd.push(o)
            this.defferd.push(o);
        } else if (status == FULFILLED || status == REJECTED) {
            this.handle(o);
        }
        return o.promise;
    }
};

/*---------------------------------------------------------------------------*/


// 没有链式调用
promise1 = new Promise(function(resolve, reject) {
  console.log('I am in callback 1');
  // setTimeout模拟异步
  setTimeout(function() {
    // balabala
    // 这里实际上可以发送一个 GET请求, 将返回的结果传给 resolve
    var a = 'ruby';
    // resolve 方法绑定到了promise1
    resolve(a);
  }, 5000);
});

promise2 = promise1.then(function(result) {
  console.log(result);
})


/*---------------------------------------------------------------------------*/

// 存在链式调用

promise1 = new Promise(function(resolve, reject) {
  setTimeout(function() {
    var a = 'ruby';
    resolve(a);
  }, 5000);
})

promise2 = promise1.then(function(result) {
  console.log('passing from resolve ' + result);
  // 返回一个新的promise对象, 但是这个 promise 并不是 promise2
  // 返回的 promise2 对象是在 Promise.prototyp.then中定义的then方法返回的
  return new Promise(function(resolve, reject) {
    setTimeout(function() {
      var b = 'python';
      resolve(b);
    }, 5000);
  })
})

// promise2 调用 then, 此时 then方法中的this就指向 promise2, 而不是最开始的那个 promise
promise3 = promise2.then(function(result) {
  console.log(result);
})


promise1.defferd = [o1]
o2 = {
  onfulfiled: function(res) {
    console.log(res);
    return new Promise(funtion(resolve, reject) {
      setTimeout(function() {
        var b = 200;
        resolve(b);
      }, 5000)
    })
  },
  onrejected: function(err) {},
  promise: new Promise(function() {})
}

o.promise == promise2


promise2.defferd = [o2]
p.defferd = promise2.defferd = [o2]

o2 = {
  onfulfiled: function(res) {
    console.log(res);
  },
  onrejected: function(err) {},
  promise: new Promise(function() {})
}

o2.promise == promise3

</code></pre>


  ]]></description>
</item>


  </channel>
</rss>
